export interface Branche {
  name: string
  slug: string
  kategorie: string
  beschreibung: string
  schmerzen: string[]
  ergebnisse: string[]
  agenten: string[]
  stundenProWoche: { klein: number; mittel: number; gross: number }
}

const branchen: Branche[] = [

  // ── MEDIZIN & GESUNDHEIT ─────────────────────────────────────────────────

  {
    name: 'Ärzte & Praxen',
    slug: 'aerzte',
    kategorie: 'Medizin & Gesundheit',
    beschreibung: 'KI-Automatisierung für Arztpraxen: Terminmanagement, Patientenkommunikation und Dokumentation ohne Mehraufwand.',
    schmerzen: ['Überfüllte Wartezimmer & Terminchaos', 'Manuelle Patientenakten & Dokumentation', 'Überlastetes Praxispersonal', 'Ineffiziente Rezeptbearbeitung'],
    ergebnisse: ['40% weniger Telefonanfragen', 'Automatische Terminerinnerungen', 'Digitale Patientenakte in Echtzeit', 'Schnellere Rezeptbearbeitung'],
    agenten: ['Der Empfänger', 'Der Planer', 'Der Schreiber', 'Der Assistent'],
    stundenProWoche: { klein: 8, mittel: 14, gross: 22 },
  },
  {
    name: 'Zahnärzte',
    slug: 'zahnaerzte',
    kategorie: 'Medizin & Gesundheit',
    beschreibung: 'Automatisierte Terminplanung, Recall-Management und Patientenkommunikation für Zahnarztpraxen.',
    schmerzen: ['Manuelle Recall-Listen', 'Hohe No-Show-Quote', 'Aufwendige Abrechnung', 'Zeitintensive Patientenkorrespondenz'],
    ergebnisse: ['Automatischer Recall per SMS/E-Mail', '30% weniger No-Shows', 'Digitale Abrechnungsvorbereitung', 'Sofortige Patientenantworten'],
    agenten: ['Der Empfänger', 'Der Planer', 'Der Buchhalter', 'Der Assistent'],
    stundenProWoche: { klein: 7, mittel: 12, gross: 20 },
  },
  {
    name: 'Physiotherapie',
    slug: 'physiotherapie',
    kategorie: 'Medizin & Gesundheit',
    beschreibung: 'Terminverwaltung, Übungsplan-Erstellung und Patientenbegleitung für Physiotherapiepraxen.',
    schmerzen: ['Aufwendige Terminkoordination', 'Manuelle Übungsplan-Erstellung', 'Fehlende Therapiedokumentation', 'Hoher Verwaltungsaufwand'],
    ergebnisse: ['Automatische Terminbuchung online', 'KI-generierte Übungspläne', 'Lückenlose Therapiedokumentation', '50% weniger Verwaltungszeit'],
    agenten: ['Der Planer', 'Der Schreiber', 'Der Assistent', 'Der Empfänger'],
    stundenProWoche: { klein: 6, mittel: 10, gross: 16 },
  },
  {
    name: 'Apotheken',
    slug: 'apotheken',
    kategorie: 'Medizin & Gesundheit',
    beschreibung: 'Bestellmanagement, Kundenkommunikation und Lageroptimierung für moderne Apotheken.',
    schmerzen: ['Komplexe Bestellprozesse', 'Manuelle Lagerführung', 'Aufwendige Kundenberatung', 'Hoher Dokumentationsaufwand'],
    ergebnisse: ['Automatische Nachbestellung', 'Echtzeit-Lagerübersicht', 'KI-Beratungsunterstützung', 'Digitale Dokumentation'],
    agenten: ['Der Einkäufer', 'Der Analyst', 'Der Empfänger', 'Der Buchhalter'],
    stundenProWoche: { klein: 8, mittel: 15, gross: 24 },
  },
  {
    name: 'Optiker',
    slug: 'optiker',
    kategorie: 'Medizin & Gesundheit',
    beschreibung: 'Terminmanagement, Bestellabwicklung und Kundenbindung für Optikerbetriebe.',
    schmerzen: ['Manuelle Terminverwaltung', 'Aufwendige Bestellprozesse', 'Fehlende Kundenbindung', 'Papierbasierte Kundendaten'],
    ergebnisse: ['Online-Terminbuchung 24/7', 'Automatische Bestellverfolgung', 'Personalisierte Kundenkommunikation', 'Digitale Kundenkartei'],
    agenten: ['Der Planer', 'Der Einkäufer', 'Der Netzwerker', 'Der Assistent'],
    stundenProWoche: { klein: 5, mittel: 9, gross: 14 },
  },
  {
    name: 'Hörgeräteakustiker',
    slug: 'hoergeraete',
    kategorie: 'Medizin & Gesundheit',
    beschreibung: 'Beratungsmanagement, Geräteverwaltung und Nachsorge für Hörgeräteakustiker.',
    schmerzen: ['Komplexe Beratungsprozesse', 'Manuelle Gerätedokumentation', 'Aufwendige Nachsorge', 'Fehlende Kundenbindung'],
    ergebnisse: ['Strukturierte Beratungsprotokolle', 'Automatische Gerätewartungshinweise', 'Systematische Nachsorge', 'Höhere Kundenzufriedenheit'],
    agenten: ['Der Empfänger', 'Der Planer', 'Der Schreiber', 'Der Assistent'],
    stundenProWoche: { klein: 5, mittel: 8, gross: 13 },
  },
  {
    name: 'Pflegedienste',
    slug: 'pflege',
    kategorie: 'Medizin & Gesundheit',
    beschreibung: 'Dienstplanung, Dokumentation und Kommunikation für ambulante und stationäre Pflegedienste.',
    schmerzen: ['Aufwendige Dienstplanung', 'Lückenhafte Pflegedokumentation', 'Hoher Koordinationsaufwand', 'Kommunikationsprobleme mit Angehörigen'],
    ergebnisse: ['KI-optimierte Dienstpläne', 'Lückenlose digitale Dokumentation', '40% weniger Koordinationsaufwand', 'Automatische Angehörigen-Updates'],
    agenten: ['Der Planer', 'Der Schreiber', 'Der Personalchef', 'Der Empfänger'],
    stundenProWoche: { klein: 10, mittel: 18, gross: 28 },
  },
  {
    name: 'Kinderbetreuung & Kitas',
    slug: 'kinderbetreuung',
    kategorie: 'Medizin & Gesundheit',
    beschreibung: 'Elternkommunikation, Belegungsplanung und Verwaltung für Kitas und Betreuungseinrichtungen.',
    schmerzen: ['Zeitaufwendige Elternkommunikation', 'Manuelle Belegungsverwaltung', 'Fehlende digitale Prozesse', 'Hoher Dokumentationsaufwand'],
    ergebnisse: ['Automatische Eltern-Newsletter', 'Digitale Belegungsübersicht', 'Papierlose Verwaltung', 'Schnelle Dokumentation'],
    agenten: ['Der Empfänger', 'Der Planer', 'Der Schreiber', 'Der Moderator'],
    stundenProWoche: { klein: 7, mittel: 12, gross: 18 },
  },
  {
    name: 'Krankenhäuser & Kliniken',
    slug: 'krankenhauser',
    kategorie: 'Medizin & Gesundheit',
    beschreibung: 'Patientenmanagement, Bettenbelegung und interne Kommunikation für Kliniken.',
    schmerzen: ['Komplexe Bettenbelegungsplanung', 'Aufwendige Patientenaufnahme', 'Ineffiziente interne Kommunikation', 'Hoher Dokumentationsaufwand'],
    ergebnisse: ['KI-optimierte Belegungsplanung', 'Digitale Patientenaufnahme', 'Strukturierte interne Kommunikation', 'Automatisierte Dokumentation'],
    agenten: ['Der Planer', 'Der Analyst', 'Der Schreiber', 'Der Moderator'],
    stundenProWoche: { klein: 20, mittel: 35, gross: 55 },
  },
  {
    name: 'Medizintechnik',
    slug: 'medizintechnik',
    kategorie: 'Medizin & Gesundheit',
    beschreibung: 'Angebotserstellung, Serviceverwaltung und Compliance-Dokumentation für Medizintechnikunternehmen.',
    schmerzen: ['Komplexe Angebotsprozesse', 'Aufwendige Servicedokumentation', 'Strenge Compliance-Anforderungen', 'Manuelle Wartungsplanung'],
    ergebnisse: ['Automatisierte Angebotserstellung', 'Lückenlose Servicedokumentation', 'Compliance-konforme Prozesse', 'Proaktive Wartungsplanung'],
    agenten: ['Der Verkäufer', 'Der Jurist', 'Der Schreiber', 'Der Techniker'],
    stundenProWoche: { klein: 10, mittel: 18, gross: 28 },
  },
  {
    name: 'Pharmazeutischer Großhandel',
    slug: 'apotheken-grosshandel',
    kategorie: 'Medizin & Gesundheit',
    beschreibung: 'Bestellabwicklung, Lagerlogistik und Compliance für pharmazeutische Großhändler.',
    schmerzen: ['Komplexe Bestellabwicklung', 'Aufwendige Lagerverwaltung', 'Strenge Regulierungsanforderungen', 'Manuelle Lieferkettensteuerung'],
    ergebnisse: ['Automatisierte Bestellprozesse', 'Echtzeit-Lagermanagement', 'Automatische Compliance-Checks', 'Optimierte Lieferkette'],
    agenten: ['Der Einkäufer', 'Der Analyst', 'Der Jurist', 'Der Integrator'],
    stundenProWoche: { klein: 15, mittel: 25, gross: 40 },
  },
  {
    name: 'Tierärzte',
    slug: 'tierarzte',
    kategorie: 'Medizin & Gesundheit',
    beschreibung: 'Terminmanagement, Patientendokumentation und Kundenkommunikation für Tierarztpraxen.',
    schmerzen: ['Überfüllter Terminkalender', 'Manuelle Patientenakten', 'Aufwendige Impferinnerungen', 'Hoher Verwaltungsaufwand'],
    ergebnisse: ['Automatische Terminverwaltung', 'Digitale Patientenakten', 'Automatische Impferinnerungen', '35% weniger Verwaltungszeit'],
    agenten: ['Der Empfänger', 'Der Planer', 'Der Schreiber', 'Der Assistent'],
    stundenProWoche: { klein: 7, mittel: 12, gross: 19 },
  },

  // ── RECHT, STEUERN & FINANZEN ────────────────────────────────────────────

  {
    name: 'Steuerberatung',
    slug: 'steuerberatung',
    kategorie: 'Recht, Steuern & Finanzen',
    beschreibung: 'Mandantenkommunikation, Dokumentenmanagement und Fristenverwaltung für Steuerberater.',
    schmerzen: ['Massiver Dokumenteneingang', 'Enge Steuerfristen', 'Aufwendige Mandantenkommunikation', 'Manuelle Belegprüfung'],
    ergebnisse: ['Automatische Dokumentenklassifikation', 'KI-gestützte Fristenüberwachung', 'Automatisierte Mandanten-Updates', 'Schnellere Belegverarbeitung'],
    agenten: ['Der Buchhalter', 'Der Jurist', 'Der Empfänger', 'Der Schreiber'],
    stundenProWoche: { klein: 12, mittel: 20, gross: 32 },
  },
  {
    name: 'Steuerberatungsgesellschaften',
    slug: 'steuerbehoerden',
    kategorie: 'Recht, Steuern & Finanzen',
    beschreibung: 'Skalierbare KI-Prozesse für große Steuerberatungsgesellschaften mit mehreren Standorten.',
    schmerzen: ['Inkonsistente Prozesse über Standorte', 'Hoher Koordinationsaufwand', 'Wissenssilos zwischen Teams', 'Skalierungsprobleme bei Mandatswachstum'],
    ergebnisse: ['Einheitliche Prozesse alle Standorte', 'Zentralisierte Koordination', 'Geteilte Wissensdatenbank', 'Skalierbare Mandatsbearbeitung'],
    agenten: ['Der Analyst', 'Der Stratege', 'Der Moderator', 'Der Buchhalter'],
    stundenProWoche: { klein: 20, mittel: 35, gross: 55 },
  },
  {
    name: 'Rechtsanwälte',
    slug: 'rechtsanwaelte',
    kategorie: 'Recht, Steuern & Finanzen',
    beschreibung: 'Mandatsverwaltung, Vertragsanalyse und Fristenkontrolle für Anwaltskanzleien.',
    schmerzen: ['Zeitaufwendige Vertragsanalyse', 'Komplexe Fristenverwaltung', 'Hoher Rechercheaufwand', 'Aufwendige Mandantenkommunikation'],
    ergebnisse: ['KI-gestützte Vertragsanalyse', 'Automatische Fristenüberwachung', 'Schnelle Rechtsprechungsrecherche', 'Strukturierte Mandantenkommunikation'],
    agenten: ['Der Jurist', 'Der Forscher', 'Der Schreiber', 'Der Empfänger'],
    stundenProWoche: { klein: 14, mittel: 24, gross: 38 },
  },
  {
    name: 'Notare',
    slug: 'notare',
    kategorie: 'Recht, Steuern & Finanzen',
    beschreibung: 'Urkundenverwaltung, Terminkoordination und Mandantenkommunikation für Notariate.',
    schmerzen: ['Aufwendige Urkundenvorbereitung', 'Komplexe Terminkoordination', 'Hoher Dokumentationsaufwand', 'Zeitintensive Mandantenbetreuung'],
    ergebnisse: ['Automatische Urkundenvorbereitung', 'Optimierte Terminplanung', 'Digitale Dokumentenverwaltung', 'Effiziente Mandantenbetreuung'],
    agenten: ['Der Jurist', 'Der Planer', 'Der Schreiber', 'Der Empfänger'],
    stundenProWoche: { klein: 10, mittel: 17, gross: 26 },
  },
  {
    name: 'Finanzberater',
    slug: 'finanzberater',
    kategorie: 'Recht, Steuern & Finanzen',
    beschreibung: 'Kundenanalyse, Berichterstellung und Compliance für unabhängige Finanzberater.',
    schmerzen: ['Aufwendige Kundenanalysen', 'Zeitintensive Berichterstellung', 'Strenge Compliance-Anforderungen', 'Manuelle Portfolio-Überwachung'],
    ergebnisse: ['KI-gestützte Kundenanalyse', 'Automatische Berichterstellung', 'Compliance-konforme Dokumentation', 'Echtzeit-Portfolio-Monitoring'],
    agenten: ['Der Analyst', 'Der Schreiber', 'Der Jurist', 'Der Stratege'],
    stundenProWoche: { klein: 10, mittel: 17, gross: 27 },
  },
  {
    name: 'Versicherungsmakler',
    slug: 'versicherungen',
    kategorie: 'Recht, Steuern & Finanzen',
    beschreibung: 'Angebotserstellung, Schadensabwicklung und Kundenbindung für Versicherungsmakler.',
    schmerzen: ['Aufwendige Angebotserstellung', 'Manuelle Schadensbearbeitung', 'Hoher Verwaltungsaufwand', 'Fehlende Kundenbindung'],
    ergebnisse: ['Automatisierte Angebotserstellung', 'Schnelle Schadensabwicklung', '50% weniger Verwaltungsaufwand', 'Systematische Kundenbindung'],
    agenten: ['Der Verkäufer', 'Der Analyst', 'Der Schreiber', 'Der Netzwerker'],
    stundenProWoche: { klein: 12, mittel: 20, gross: 32 },
  },
  {
    name: 'Banken & Sparkassen',
    slug: 'banken',
    kategorie: 'Recht, Steuern & Finanzen',
    beschreibung: 'Kundenservice, Compliance und interne Prozessautomatisierung für Banken und Sparkassen.',
    schmerzen: ['Hoher manueller Kundenservice-Aufwand', 'Komplexe Compliance-Prozesse', 'Langsame interne Abläufe', 'Papierbasierte Prozesse'],
    ergebnisse: ['KI-Kundenservice 24/7', 'Automatische Compliance-Checks', 'Schnellere Genehmigungsprozesse', 'Vollständig digitale Prozesse'],
    agenten: ['Der Empfänger', 'Der Jurist', 'Der Analyst', 'Der Integrator'],
    stundenProWoche: { klein: 20, mittel: 35, gross: 55 },
  },
  {
    name: 'Unternehmensberater',
    slug: 'unternehmensberater',
    kategorie: 'Recht, Steuern & Finanzen',
    beschreibung: 'Recherche, Berichterstellung und Projektmanagement für Unternehmensberatungen.',
    schmerzen: ['Zeitaufwendige Marktrecherchen', 'Aufwendige Berichterstellung', 'Komplexes Projektmanagement', 'Wissensmanagement-Probleme'],
    ergebnisse: ['KI-gestützte Marktanalysen', 'Automatisierte Berichterstellung', 'Strukturiertes Projektmanagement', 'Zentrale Wissensdatenbank'],
    agenten: ['Der Forscher', 'Der Analyst', 'Der Stratege', 'Der Schreiber'],
    stundenProWoche: { klein: 12, mittel: 20, gross: 32 },
  },
  {
    name: 'Digitalberatung',
    slug: 'unternehmensberatung-digital',
    kategorie: 'Recht, Steuern & Finanzen',
    beschreibung: 'Projektabwicklung, Kundenreporting und Wissensmanagement für Digital-Agenturen.',
    schmerzen: ['Aufwendiges Kundenreporting', 'Komplexe Projektkommunikation', 'Ineffizientes Wissensmanagement', 'Hoher Angebotserstellungsaufwand'],
    ergebnisse: ['Automatische Projektberichte', 'Strukturierte Kundenkommunikation', 'KI-Wissensdatenbank', 'Schnelle Angebotserstellung'],
    agenten: ['Der Stratege', 'Der Schreiber', 'Der Analyst', 'Der Verkäufer'],
    stundenProWoche: { klein: 10, mittel: 17, gross: 27 },
  },

  // ── HANDWERK & BAU ───────────────────────────────────────────────────────

  {
    name: 'Elektriker & Elektrobetriebe',
    slug: 'elektriker',
    kategorie: 'Handwerk & Bau',
    beschreibung: 'Auftragsmanagement, Angebotserstellung und Kundenkommunikation für Elektrobetriebe.',
    schmerzen: ['Auftragsflut ohne System', 'Manuelle Angebotserstellung', 'Aufwendige Materialdisposition', 'Fehlende Kundenkommunikation'],
    ergebnisse: ['Digitales Auftragsmanagement', 'Automatisierte Angebote in Minuten', 'KI-Materialdisposition', 'Automatische Kundenupdates'],
    agenten: ['Der Planer', 'Der Verkäufer', 'Der Einkäufer', 'Der Empfänger'],
    stundenProWoche: { klein: 8, mittel: 14, gross: 22 },
  },
  {
    name: 'Sanitär & Heizung',
    slug: 'sanitaer-heizung',
    kategorie: 'Handwerk & Bau',
    beschreibung: 'Notfallmanagement, Wartungsplanung und Angebotserstellung für SHK-Betriebe.',
    schmerzen: ['Chaotisches Notfallmanagement', 'Manuelle Wartungsplanung', 'Aufwendige Angebotserstellung', 'Materialengpässe'],
    ergebnisse: ['Strukturiertes Notfallsystem', 'Automatische Wartungserinnerungen', 'Schnelle digitale Angebote', 'Optimierte Materialdisposition'],
    agenten: ['Der Planer', 'Der Verkäufer', 'Der Einkäufer', 'Der Techniker'],
    stundenProWoche: { klein: 8, mittel: 13, gross: 21 },
  },
  {
    name: 'Maler & Lackierer',
    slug: 'maler',
    kategorie: 'Handwerk & Bau',
    beschreibung: 'Angebotserstellung, Projektplanung und Kundenkommunikation für Malerbetriebe.',
    schmerzen: ['Zeitaufwendige Angebotserstellung', 'Schlechte Projektplanung', 'Fehlende Kundenbindung', 'Materialverschwendung'],
    ergebnisse: ['Angebote in 15 Minuten', 'KI-gestützte Projektplanung', 'Automatische Kundenkommunikation', 'Optimierter Materialeinsatz'],
    agenten: ['Der Verkäufer', 'Der Planer', 'Der Empfänger', 'Der Einkäufer'],
    stundenProWoche: { klein: 6, mittel: 11, gross: 17 },
  },
  {
    name: 'Schreiner & Tischler',
    slug: 'schreiner',
    kategorie: 'Handwerk & Bau',
    beschreibung: 'Auftragsplanung, Materialbestellung und Kundenkommunikation für Schreinerbetriebe.',
    schmerzen: ['Komplexe Auftragsplanung', 'Aufwendige Materialbestellung', 'Lange Lieferzeiten', 'Fehlende Kundenkommunikation'],
    ergebnisse: ['Digitale Auftragsplanung', 'Automatische Materialbestellung', 'Lieferketten-Transparenz', 'Proaktive Kundenkommunikation'],
    agenten: ['Der Planer', 'Der Einkäufer', 'Der Schreiber', 'Der Empfänger'],
    stundenProWoche: { klein: 7, mittel: 12, gross: 19 },
  },
  {
    name: 'Bauunternehmen',
    slug: 'bauunternehmen',
    kategorie: 'Handwerk & Bau',
    beschreibung: 'Projektsteuerung, Nachunternehmerverwaltung und Dokumentation für Bauunternehmen.',
    schmerzen: ['Komplexe Projektsteuerung', 'Schwierige Nachunternehmerverwaltung', 'Lückenhafte Baudokumentation', 'Kostenüberschreitungen'],
    ergebnisse: ['KI-Projektsteuerung in Echtzeit', 'Digitale Nachunternehmerverwaltung', 'Vollständige Baudokumentation', 'Frühzeitige Kostenwarnungen'],
    agenten: ['Der Planer', 'Der Analyst', 'Der Schreiber', 'Der Einkäufer'],
    stundenProWoche: { klein: 15, mittel: 25, gross: 40 },
  },
  {
    name: 'Architekten',
    slug: 'architekten',
    kategorie: 'Handwerk & Bau',
    beschreibung: 'Projektdokumentation, Behördenkommunikation und Kundenpräsentationen für Architekturbüros.',
    schmerzen: ['Aufwendige Behördenkommunikation', 'Komplexe Projektverwaltung', 'Zeitintensive Kundenpräsentationen', 'Viele Planungsvarianten'],
    ergebnisse: ['Automatisierte Behördenkorrespondenz', 'Strukturiertes Projektmanagement', 'KI-gestützte Präsentationen', 'Schnelle Planungsvarianten'],
    agenten: ['Der Schreiber', 'Der Planer', 'Der Stratege', 'Der Empfänger'],
    stundenProWoche: { klein: 10, mittel: 17, gross: 27 },
  },
  {
    name: 'Ingenieurbüros',
    slug: 'ingenieurbueros',
    kategorie: 'Handwerk & Bau',
    beschreibung: 'Technische Dokumentation, Projektmanagement und Normenrecherche für Ingenieurbüros.',
    schmerzen: ['Aufwendige technische Dokumentation', 'Zeitintensive Normenrecherche', 'Komplexe Projektkoordination', 'Aufwendige Berichterstellung'],
    ergebnisse: ['Automatisierte technische Berichte', 'KI-Normenrecherche', 'Digitale Projektkoordination', 'Schnelle Berichterstellung'],
    agenten: ['Der Schreiber', 'Der Forscher', 'Der Analyst', 'Der Planer'],
    stundenProWoche: { klein: 10, mittel: 18, gross: 28 },
  },
  {
    name: 'Immobilienentwicklung',
    slug: 'immobilien-entwicklung',
    kategorie: 'Handwerk & Bau',
    beschreibung: 'Projektentwicklung, Investorenreporting und Behördenmanagement für Immobilienentwickler.',
    schmerzen: ['Komplexes Behördenmanagement', 'Aufwendiges Investorenreporting', 'Lange Genehmigungsprozesse', 'Viele Projektbeteiligte'],
    ergebnisse: ['Strukturiertes Behördenmanagement', 'Automatische Investorenberichte', 'Beschleunigte Genehmigungen', 'Zentrales Projektportal'],
    agenten: ['Der Stratege', 'Der Analyst', 'Der Jurist', 'Der Schreiber'],
    stundenProWoche: { klein: 15, mittel: 25, gross: 40 },
  },

  // ── INDUSTRIE & PRODUKTION ───────────────────────────────────────────────

  {
    name: 'Industrie & Produktion',
    slug: 'industrie-produktion',
    kategorie: 'Industrie & Produktion',
    beschreibung: 'Produktionsplanung, Qualitätssicherung und Lieferkettenmanagement für Industriebetriebe.',
    schmerzen: ['Ungeplante Produktionsausfälle', 'Manuelle Qualitätsprüfung', 'Ineffiziente Lieferkette', 'Hoher Dokumentationsaufwand'],
    ergebnisse: ['Vorausschauende Wartungsplanung', 'Automatisierte Qualitätschecks', 'Optimierte Lieferkette', 'Digitale Produktionsdokumentation'],
    agenten: ['Der Planer', 'Der Analyst', 'Der Einkäufer', 'Der Techniker'],
    stundenProWoche: { klein: 18, mittel: 30, gross: 48 },
  },
  {
    name: 'Maschinenbau',
    slug: 'maschinenbau',
    kategorie: 'Industrie & Produktion',
    beschreibung: 'Angebotserstellung, technische Dokumentation und Servicemanagement für Maschinenbauunternehmen.',
    schmerzen: ['Komplexe Angebotskalkulation', 'Aufwendige technische Dokumentation', 'Manuelle Serviceverwaltung', 'Lange Lieferzeiten'],
    ergebnisse: ['KI-gestützte Angebotskalkulation', 'Automatisierte technische Dokumentation', 'Digitales Servicemanagement', 'Optimierte Lieferkette'],
    agenten: ['Der Verkäufer', 'Der Schreiber', 'Der Techniker', 'Der Einkäufer'],
    stundenProWoche: { klein: 14, mittel: 24, gross: 38 },
  },
  {
    name: 'Chemie & Pharma',
    slug: 'chemie',
    kategorie: 'Industrie & Produktion',
    beschreibung: 'Compliance-Management, Qualitätsdokumentation und Forschungsunterstützung für Chemie- und Pharmaunternehmen.',
    schmerzen: ['Strenge Regulatory-Anforderungen', 'Aufwendige Qualitätsdokumentation', 'Komplexe Compliance-Prozesse', 'Hoher Forschungsaufwand'],
    ergebnisse: ['Automatisierte Compliance-Dokumentation', 'Lückenlose Qualitätssicherung', 'KI-Regulatory-Unterstützung', 'Schnellere Forschungsauswertung'],
    agenten: ['Der Jurist', 'Der Schreiber', 'Der Forscher', 'Der Analyst'],
    stundenProWoche: { klein: 16, mittel: 28, gross: 44 },
  },
  {
    name: 'Lebensmittelproduktion',
    slug: 'lebensmittelproduktion',
    kategorie: 'Industrie & Produktion',
    beschreibung: 'HACCP-Dokumentation, Lieferantenmanagement und Qualitätssicherung für Lebensmittelproduzenten.',
    schmerzen: ['Aufwendige HACCP-Dokumentation', 'Komplexes Lieferantenmanagement', 'Strenge Hygienevorschriften', 'Hoher Rückverfolgungsaufwand'],
    ergebnisse: ['Automatische HACCP-Protokolle', 'Digitales Lieferantenmanagement', 'KI-Hygieneüberwachung', 'Lückenlose Rückverfolgung'],
    agenten: ['Der Jurist', 'Der Einkäufer', 'Der Analyst', 'Der Schreiber'],
    stundenProWoche: { klein: 14, mittel: 24, gross: 38 },
  },
  {
    name: 'Textil & Mode',
    slug: 'textilproduktion',
    kategorie: 'Industrie & Produktion',
    beschreibung: 'Kollektionsplanung, Lieferantenmanagement und Trendanalyse für die Textilbranche.',
    schmerzen: ['Aufwendige Kollektionsplanung', 'Komplexes Lieferantenmanagement', 'Schnelle Trendveränderungen', 'Hoher Lagerbestandsaufwand'],
    ergebnisse: ['KI-gestützte Kollektionsplanung', 'Digitales Lieferantenmanagement', 'Automatische Trendanalysen', 'Optimierter Lagerbestand'],
    agenten: ['Der Stratege', 'Der Einkäufer', 'Der Analyst', 'Der Forscher'],
    stundenProWoche: { klein: 12, mittel: 20, gross: 32 },
  },
  {
    name: 'Möbel & Einrichtung',
    slug: 'moebel',
    kategorie: 'Industrie & Produktion',
    beschreibung: 'Auftragsmanagement, Produktkonfiguration und Lieferlogistik für Möbelhersteller und -händler.',
    schmerzen: ['Komplexe Produktkonfigurationen', 'Aufwendige Lieferplanung', 'Hoher Reklamationsaufwand', 'Manuelle Auftragsbearbeitung'],
    ergebnisse: ['Digitale Produktkonfiguration', 'Optimierte Lieferplanung', 'Automatisches Reklamationsmanagement', 'Schnelle Auftragsbearbeitung'],
    agenten: ['Der Verkäufer', 'Der Planer', 'Der Einkäufer', 'Der Empfänger'],
    stundenProWoche: { klein: 10, mittel: 17, gross: 27 },
  },
  {
    name: 'Elektronik & Technologie',
    slug: 'elektronik',
    kategorie: 'Industrie & Produktion',
    beschreibung: 'Produktentwicklung, Qualitätssicherung und technischer Support für Elektronikunternehmen.',
    schmerzen: ['Schnelle Produktzyklen', 'Komplexe Qualitätssicherung', 'Hoher technischer Supportaufwand', 'Aufwendige Dokumentation'],
    ergebnisse: ['KI-gestützte Qualitätsprüfung', 'Automatisierter technischer Support', 'Schnelle Produktdokumentation', 'Beschleunigte Entwicklungszyklen'],
    agenten: ['Der Techniker', 'Der Analyst', 'Der Schreiber', 'Der Forscher'],
    stundenProWoche: { klein: 14, mittel: 24, gross: 38 },
  },
  {
    name: 'Automobilzulieferer',
    slug: 'automobilzulieferer',
    kategorie: 'Industrie & Produktion',
    beschreibung: 'Qualitätsmanagement, Lieferantenentwicklung und Produktionsdokumentation für Automobilzulieferer.',
    schmerzen: ['Strenge OEM-Qualitätsanforderungen', 'Komplexe Lieferantenentwicklung', 'Hoher Dokumentationsaufwand', 'Enge Liefertoleranzen'],
    ergebnisse: ['Automatische Qualitätsdokumentation', 'Digitale Lieferantenentwicklung', 'KI-Compliance-Monitoring', 'Proaktives Lieferkettenmanagement'],
    agenten: ['Der Analyst', 'Der Jurist', 'Der Einkäufer', 'Der Schreiber'],
    stundenProWoche: { klein: 16, mittel: 28, gross: 44 },
  },
  {
    name: 'Luft- & Raumfahrt',
    slug: 'luft-raumfahrt',
    kategorie: 'Industrie & Produktion',
    beschreibung: 'Zertifizierungsmanagement, technische Dokumentation und Compliance für Luft- und Raumfahrtunternehmen.',
    schmerzen: ['Extrem strenge Zertifizierungsanforderungen', 'Aufwendige technische Dokumentation', 'Komplexe Compliance-Prozesse', 'Hohe Sicherheitsanforderungen'],
    ergebnisse: ['Strukturiertes Zertifizierungsmanagement', 'Automatisierte technische Dokumentation', 'Lückenlose Compliance-Nachverfolgung', 'Digitale Sicherheitsprotokolle'],
    agenten: ['Der Jurist', 'Der Schreiber', 'Der Analyst', 'Der Sicherheitschef'],
    stundenProWoche: { klein: 20, mittel: 35, gross: 55 },
  },
  {
    name: 'Verteidigung & Sicherheit',
    slug: 'verteidigung-sicherheit',
    kategorie: 'Industrie & Produktion',
    beschreibung: 'Compliance, Dokumentenmanagement und Projektsteuerung für Verteidigungsunternehmen.',
    schmerzen: ['Höchste Geheimhaltungsanforderungen', 'Komplexe Compliance-Prozesse', 'Aufwendige Projektsteuerung', 'Strenge Exportkontrolle'],
    ergebnisse: ['Sichere Dokumentenverwaltung', 'Automatisierte Compliance-Checks', 'Strukturierte Projektsteuerung', 'KI-gestützte Exportkontrolle'],
    agenten: ['Der Sicherheitschef', 'Der Jurist', 'Der Analyst', 'Der Schreiber'],
    stundenProWoche: { klein: 18, mittel: 30, gross: 48 },
  },
  {
    name: 'Bergbau & Rohstoffe',
    slug: 'bergbau',
    kategorie: 'Industrie & Produktion',
    beschreibung: 'Betriebsplanung, Sicherheitsmanagement und Umweltdokumentation für Bergbauunternehmen.',
    schmerzen: ['Komplexe Betriebsplanung', 'Strenge Sicherheitsvorschriften', 'Aufwendige Umweltdokumentation', 'Hoher Koordinationsaufwand'],
    ergebnisse: ['Optimierte Betriebsplanung', 'Automatisches Sicherheitsmonitoring', 'Digitale Umweltdokumentation', 'Zentrale Koordinationsplattform'],
    agenten: ['Der Planer', 'Der Sicherheitschef', 'Der Jurist', 'Der Analyst'],
    stundenProWoche: { klein: 16, mittel: 27, gross: 43 },
  },
  {
    name: 'Druckereien',
    slug: 'druckereien',
    kategorie: 'Industrie & Produktion',
    beschreibung: 'Auftragsmanagement, Druckvorstufe und Kundenkommunikation für Druckbetriebe.',
    schmerzen: ['Aufwendiges Auftragsmanagement', 'Manuelle Druckvorbereitung', 'Fehlerhafte Kundenaufträge', 'Hoher Korrekturaufwand'],
    ergebnisse: ['Digitales Auftragsmanagement', 'KI-gestützte Druckvorstufe', 'Automatische Auftragsprüfung', 'Schnellere Korrekturprozesse'],
    agenten: ['Der Empfänger', 'Der Planer', 'Der Verkäufer', 'Der Techniker'],
    stundenProWoche: { klein: 8, mittel: 14, gross: 22 },
  },

  // ── HANDEL & E-COMMERCE ──────────────────────────────────────────────────

  {
    name: 'Einzelhandel',
    slug: 'einzelhandel',
    kategorie: 'Handel & E-Commerce',
    beschreibung: 'Bestandsmanagement, Kundenbindung und Kassenabschluss für Einzelhändler.',
    schmerzen: ['Manuelle Bestandsverwaltung', 'Aufwendige Kassenabschlüsse', 'Fehlende Kundenbindung', 'Hoher Personalaufwand'],
    ergebnisse: ['Automatisches Bestandsmanagement', 'Digitale Kassenabschlüsse', 'KI-Kundenbindungsprogramm', '30% weniger Personalaufwand'],
    agenten: ['Der Einkäufer', 'Der Analyst', 'Der Netzwerker', 'Der Buchhalter'],
    stundenProWoche: { klein: 10, mittel: 17, gross: 27 },
  },
  {
    name: 'Großhandel',
    slug: 'grosshandel',
    kategorie: 'Handel & E-Commerce',
    beschreibung: 'Bestellabwicklung, Lieferantenmanagement und Lagerverwaltung für Großhändler.',
    schmerzen: ['Aufwendige Bestellabwicklung', 'Komplexes Lieferantenmanagement', 'Manuelle Lagerverwaltung', 'Hoher Kommunikationsaufwand'],
    ergebnisse: ['Automatisierte Bestellabwicklung', 'Digitales Lieferantenmanagement', 'KI-Lagerverwaltung', 'Automatische Kundenkommunikation'],
    agenten: ['Der Einkäufer', 'Der Analyst', 'Der Empfänger', 'Der Buchhalter'],
    stundenProWoche: { klein: 14, mittel: 24, gross: 38 },
  },
  {
    name: 'E-Commerce',
    slug: 'e-commerce',
    kategorie: 'Handel & E-Commerce',
    beschreibung: 'Produktdatenpflege, Kundensupport und Retourenmanagement für Online-Händler.',
    schmerzen: ['Aufwendige Produktdatenpflege', 'Hoher Kundensupport-Aufwand', 'Komplexes Retourenmanagement', 'Viele Marktplätze gleichzeitig'],
    ergebnisse: ['KI-Produktdatenpflege', 'Automatisierter Kundensupport 24/7', 'Digitales Retourenmanagement', 'Zentrale Marktplatzverwaltung'],
    agenten: ['Der Schreiber', 'Der Empfänger', 'Der Analyst', 'Der Integrator'],
    stundenProWoche: { klein: 14, mittel: 24, gross: 38 },
  },
  {
    name: 'KFZ-Werkstätten',
    slug: 'kfz-werkstaetten',
    kategorie: 'Handel & E-Commerce',
    beschreibung: 'Terminmanagement, Kostenvoranschläge und Kundenkommunikation für KFZ-Werkstätten.',
    schmerzen: ['Überfüllter Terminkalender', 'Aufwendige Kostenvoranschläge', 'Schlechte Kundenkommunikation', 'Manuelle Teilebestellung'],
    ergebnisse: ['Online-Terminbuchung 24/7', 'Digitale Kostenvoranschläge', 'Automatische Kundenupdates', 'Schnelle Teilebestellung'],
    agenten: ['Der Planer', 'Der Verkäufer', 'Der Einkäufer', 'Der Empfänger'],
    stundenProWoche: { klein: 8, mittel: 14, gross: 22 },
  },
  {
    name: 'KFZ-Handel',
    slug: 'kfz-handel',
    kategorie: 'Handel & E-Commerce',
    beschreibung: 'Fahrzeugverwaltung, Lead-Management und Finanzierungsberatung für Autohändler.',
    schmerzen: ['Aufwendige Fahrzeugverwaltung', 'Ineffizientes Lead-Management', 'Lange Verkaufsprozesse', 'Manuelle Finanzierungsberechnung'],
    ergebnisse: ['Digitale Fahrzeugverwaltung', 'KI-Lead-Management', 'Beschleunigte Verkaufsprozesse', 'Automatische Finanzierungsangebote'],
    agenten: ['Der Verkäufer', 'Der Analyst', 'Der Empfänger', 'Der Netzwerker'],
    stundenProWoche: { klein: 10, mittel: 17, gross: 27 },
  },

  // ── IMMOBILIEN & VERWALTUNG ──────────────────────────────────────────────

  {
    name: 'Immobilienmakler',
    slug: 'immobilienmakler',
    kategorie: 'Immobilien & Verwaltung',
    beschreibung: 'Exposé-Erstellung, Lead-Qualifizierung und Besichtigungsmanagement für Immobilienmakler.',
    schmerzen: ['Aufwendige Exposé-Erstellung', 'Unqualifizierte Anfragen', 'Zeitintensive Besichtigungsplanung', 'Hoher Kommunikationsaufwand'],
    ergebnisse: ['KI-generierte Exposés in Minuten', 'Automatische Lead-Qualifizierung', 'Optimierte Besichtigungsplanung', 'Automatische Interessentenkommunikation'],
    agenten: ['Der Schreiber', 'Der Verkäufer', 'Der Planer', 'Der Empfänger'],
    stundenProWoche: { klein: 10, mittel: 17, gross: 27 },
  },
  {
    name: 'Hausverwaltungen',
    slug: 'hausverwaltungen',
    kategorie: 'Immobilien & Verwaltung',
    beschreibung: 'Mieterverwaltung, Nebenkostenabrechnung und Instandhaltungsplanung für Hausverwaltungen.',
    schmerzen: ['Aufwendige Nebenkostenabrechnung', 'Viele Mieteranfragen', 'Komplexe Instandhaltungsplanung', 'Papierbasierte Prozesse'],
    ergebnisse: ['Automatische Nebenkostenabrechnung', 'KI-Mieterservice 24/7', 'Digitale Instandhaltungsplanung', 'Vollständig papierlose Verwaltung'],
    agenten: ['Der Buchhalter', 'Der Empfänger', 'Der Planer', 'Der Jurist'],
    stundenProWoche: { klein: 12, mittel: 20, gross: 32 },
  },
  {
    name: 'Franchise-Systeme',
    slug: 'franchise',
    kategorie: 'Immobilien & Verwaltung',
    beschreibung: 'Franchise-Kommunikation, Performance-Monitoring und Wissenstransfer für Franchise-Systeme.',
    schmerzen: ['Inkonsistente Franchise-Kommunikation', 'Schwieriges Performance-Monitoring', 'Aufwendiger Wissenstransfer', 'Unterschiedliche Qualitätsstandards'],
    ergebnisse: ['Einheitliche Franchise-Kommunikation', 'Echtzeit-Performance-Monitoring', 'Automatischer Wissensstransfer', 'Konsistente Qualitätsstandards'],
    agenten: ['Der Moderator', 'Der Analyst', 'Der Trainer', 'Der Stratege'],
    stundenProWoche: { klein: 14, mittel: 24, gross: 38 },
  },
  {
    name: 'Stadtverwaltungen & Behörden',
    slug: 'stadtverwaltungen',
    kategorie: 'Immobilien & Verwaltung',
    beschreibung: 'Bürgerkommunikation, Antragsverwaltung und interne Prozessautomatisierung für öffentliche Verwaltungen.',
    schmerzen: ['Hoher Bürgerkommunikationsaufwand', 'Langsame Antragsprozesse', 'Papierbasierte Verwaltung', 'Ineffiziente interne Abläufe'],
    ergebnisse: ['Digitaler Bürgerservice 24/7', 'Beschleunigte Antragsprozesse', 'Papierlose Verwaltung', 'Optimierte interne Abläufe'],
    agenten: ['Der Empfänger', 'Der Schreiber', 'Der Planer', 'Der Analyst'],
    stundenProWoche: { klein: 20, mittel: 35, gross: 55 },
  },

  // ── LOGISTIK & TRANSPORT ─────────────────────────────────────────────────

  {
    name: 'Logistik & Spedition',
    slug: 'logistik',
    kategorie: 'Logistik & Transport',
    beschreibung: 'Tourenplanung, Sendungsverfolgung und Dokumentenmanagement für Speditionsunternehmen.',
    schmerzen: ['Ineffiziente Tourenplanung', 'Aufwendige Sendungsverfolgung', 'Hoher Dokumentationsaufwand', 'Kommunikationsprobleme mit Kunden'],
    ergebnisse: ['KI-optimierte Tourenplanung', 'Automatische Sendungsverfolgung', 'Digitale Transportdokumente', 'Automatische Kundeninformation'],
    agenten: ['Der Planer', 'Der Analyst', 'Der Empfänger', 'Der Schreiber'],
    stundenProWoche: { klein: 14, mittel: 24, gross: 38 },
  },
  {
    name: 'Transport & Fuhrpark',
    slug: 'transport',
    kategorie: 'Logistik & Transport',
    beschreibung: 'Fuhrparkverwaltung, Fahrerkoordination und Wartungsplanung für Transportunternehmen.',
    schmerzen: ['Aufwendige Fuhrparkverwaltung', 'Schwierige Fahrerkoordination', 'Manuelle Wartungsplanung', 'Hohe Kraftstoffkosten'],
    ergebnisse: ['Digitale Fuhrparkverwaltung', 'Automatische Fahrerkoordination', 'Proaktive Wartungsplanung', 'KI-Kraftstoffoptimierung'],
    agenten: ['Der Planer', 'Der Analyst', 'Der Techniker', 'Der Personalchef'],
    stundenProWoche: { klein: 10, mittel: 17, gross: 27 },
  },
  {
    name: 'Post & Kurierdienste',
    slug: 'postdienste',
    kategorie: 'Logistik & Transport',
    beschreibung: 'Routenoptimierung, Sendungsmanagement und Kundenkommunikation für Kurierdienste.',
    schmerzen: ['Aufwendige Routenplanung', 'Hohe Sendungsvolumen', 'Viele Kundennachfragen', 'Hoher Koordinationsaufwand'],
    ergebnisse: ['KI-Routenoptimierung', 'Automatisches Sendungsmanagement', 'Self-Service Kundenkommunikation', 'Zentrale Koordinationsplattform'],
    agenten: ['Der Planer', 'Der Empfänger', 'Der Analyst', 'Der Integrator'],
    stundenProWoche: { klein: 12, mittel: 20, gross: 32 },
  },

  // ── IT & TECHNOLOGIE ─────────────────────────────────────────────────────

  {
    name: 'IT-Dienstleister',
    slug: 'it-dienstleister',
    kategorie: 'IT & Technologie',
    beschreibung: 'Ticketsystem, Kundensupport und Projektmanagement für IT-Dienstleister.',
    schmerzen: ['Überfülltes Ticketsystem', 'Reaktiver statt proaktiver Support', 'Aufwendiges Projektmanagement', 'Fehlende Wissensdatenbank'],
    ergebnisse: ['KI-Ticketpriorisierung', 'Proaktives Monitoring & Alerting', 'Strukturiertes Projektmanagement', 'Automatisch wachsende Wissensdatenbank'],
    agenten: ['Der Techniker', 'Der Empfänger', 'Der Planer', 'Der Forscher'],
    stundenProWoche: { klein: 12, mittel: 20, gross: 32 },
  },
  {
    name: 'Softwareentwicklung',
    slug: 'softwareentwicklung',
    kategorie: 'IT & Technologie',
    beschreibung: 'Entwicklungsdokumentation, Projektmanagement und Kundenkommunikation für Softwareunternehmen.',
    schmerzen: ['Aufwendige technische Dokumentation', 'Kommunikationslücken mit Kunden', 'Langsame Releasezyklen', 'Mangelndes Wissensmanagement'],
    ergebnisse: ['Automatische Code-Dokumentation', 'Strukturierte Kundenkommunikation', 'Beschleunigte Releasezyklen', 'Zentrale Wissensdatenbank'],
    agenten: ['Der Schreiber', 'Der Techniker', 'Der Planer', 'Der Empfänger'],
    stundenProWoche: { klein: 12, mittel: 20, gross: 32 },
  },
  {
    name: 'Telekommunikation',
    slug: 'telekommunikation',
    kategorie: 'IT & Technologie',
    beschreibung: 'Kundenservice, Vertragsmanagement und Netzwerkdokumentation für Telekommunikationsunternehmen.',
    schmerzen: ['Hoher Kundenservice-Aufwand', 'Komplexes Vertragsmanagement', 'Aufwendige Netzwerkdokumentation', 'Hohe Churn-Rate'],
    ergebnisse: ['KI-Kundenservice 24/7', 'Automatisches Vertragsmanagement', 'Digitale Netzwerkdokumentation', 'Proaktive Churn-Prävention'],
    agenten: ['Der Empfänger', 'Der Jurist', 'Der Analyst', 'Der Techniker'],
    stundenProWoche: { klein: 16, mittel: 27, gross: 43 },
  },
  {
    name: 'Wasserwirtschaft & Umwelt',
    slug: 'wasserwirtschaft',
    kategorie: 'IT & Technologie',
    beschreibung: 'Betriebsüberwachung, Compliance-Dokumentation und Berichterstellung für Wasserversorger.',
    schmerzen: ['Aufwendige Compliance-Dokumentation', 'Komplexe Betriebsüberwachung', 'Strenge Regulierungsanforderungen', 'Hoher Berichtsaufwand'],
    ergebnisse: ['Automatische Compliance-Berichte', 'Echtzeit-Betriebsüberwachung', 'KI-Regulierungsunterstützung', 'Automatisierte Behördenberichte'],
    agenten: ['Der Analyst', 'Der Jurist', 'Der Schreiber', 'Der Sicherheitschef'],
    stundenProWoche: { klein: 12, mittel: 20, gross: 32 },
  },
  {
    name: 'Erneuerbare Energien',
    slug: 'erneuerbare-energien',
    kategorie: 'IT & Technologie',
    beschreibung: 'Anlagenmonitoring, Fördermittelmanagement und Kundenkommunikation für Erneuerbare-Energien-Unternehmen.',
    schmerzen: ['Komplexes Anlagenmonitoring', 'Aufwendiges Fördermittelmanagement', 'Viele Genehmigungsprozesse', 'Hoher Dokumentationsaufwand'],
    ergebnisse: ['Automatisches Anlagenmonitoring', 'KI-Fördermittelrecherche', 'Strukturiertes Genehmigungsmanagement', 'Digitale Compliance-Dokumentation'],
    agenten: ['Der Analyst', 'Der Forscher', 'Der Jurist', 'Der Schreiber'],
    stundenProWoche: { klein: 12, mittel: 20, gross: 32 },
  },
  {
    name: 'Startups & Scale-ups',
    slug: 'startups',
    kategorie: 'IT & Technologie',
    beschreibung: 'Investorenkommunikation, Wachstumsprozesse und Teammanagement für schnell wachsende Startups.',
    schmerzen: ['Aufwendige Investorenkommunikation', 'Skalierungsprobleme', 'Fehlende Prozessstrukturen', 'Hoher Recruitingaufwand'],
    ergebnisse: ['Automatisierte Investorenberichte', 'Skalierbare Prozessstrukturen', 'KI-Prozessoptimierung', 'Effizientes Recruiting'],
    agenten: ['Der Stratege', 'Der Schreiber', 'Der Analyst', 'Der Personalchef'],
    stundenProWoche: { klein: 14, mittel: 24, gross: 38 },
  },

  // ── MARKETING & KOMMUNIKATION ────────────────────────────────────────────

  {
    name: 'Marketing-Agenturen',
    slug: 'marketing-agenturen',
    kategorie: 'Marketing & Kommunikation',
    beschreibung: 'Content-Erstellung, Kampagnenmanagement und Kundenreporting für Marketing-Agenturen.',
    schmerzen: ['Aufwendige Content-Erstellung', 'Zeitintensives Kampagnenreporting', 'Schwierige Kundenkommunikation', 'Viele parallele Projekte'],
    ergebnisse: ['KI-Content-Erstellung in Minuten', 'Automatisches Kampagnenreporting', 'Strukturierte Kundenkommunikation', 'Effizientes Multiprojektmanagement'],
    agenten: ['Der Schreiber', 'Der Analyst', 'Der Regisseur', 'Der Botschafter'],
    stundenProWoche: { klein: 14, mittel: 24, gross: 38 },
  },
  {
    name: 'Werbeagenturen',
    slug: 'werbeagenturen',
    kategorie: 'Marketing & Kommunikation',
    beschreibung: 'Briefing-Management, Kreativprozesse und Kundenpräsentationen für Werbeagenturen.',
    schmerzen: ['Unstrukturierte Briefingprozesse', 'Zeitaufwendige Präsentationen', 'Schwieriges Feedbackmanagement', 'Hoher Korrekturaufwand'],
    ergebnisse: ['Strukturierte Briefingprozesse', 'KI-gestützte Präsentationen', 'Systematisches Feedbackmanagement', 'Reduzierter Korrekturaufwand'],
    agenten: ['Der Schreiber', 'Der Regisseur', 'Der Moderator', 'Der Stratege'],
    stundenProWoche: { klein: 12, mittel: 20, gross: 32 },
  },
  {
    name: 'PR-Agenturen',
    slug: 'pr-agenturen',
    kategorie: 'Marketing & Kommunikation',
    beschreibung: 'Pressemitteilungen, Medienmonitoring und Krisenkommunikation für PR-Agenturen.',
    schmerzen: ['Aufwendige Pressemitteilungen', 'Manuelles Medienmonitoring', 'Reaktive Krisenkommunikation', 'Hoher Rechercheaufwand'],
    ergebnisse: ['KI-Pressemitteilungen in Minuten', 'Automatisches Medienmonitoring', 'Proaktive Krisenkommunikation', 'Schnelle Hintergrundrecherche'],
    agenten: ['Der Schreiber', 'Der Forscher', 'Der Botschafter', 'Der Späher'],
    stundenProWoche: { klein: 12, mittel: 20, gross: 32 },
  },
  {
    name: 'Unternehmenskommunikation',
    slug: 'unternehmenskommunikation',
    kategorie: 'Marketing & Kommunikation',
    beschreibung: 'Interne Kommunikation, Mitarbeiterzeitschrift und CEO-Kommunikation für Unternehmen.',
    schmerzen: ['Aufwendige interne Kommunikation', 'Zeitintensive Newsletter-Erstellung', 'Inkonsistente Botschaften', 'Informationssilos'],
    ergebnisse: ['Automatisierte interne Kommunikation', 'KI-generierte Newsletter', 'Konsistente Unternehmenskommunikation', 'Zentrales Informationsportal'],
    agenten: ['Der Schreiber', 'Der Moderator', 'Der Botschafter', 'Der Stratege'],
    stundenProWoche: { klein: 8, mittel: 14, gross: 22 },
  },
  {
    name: 'Verlage & Medien',
    slug: 'verlage',
    kategorie: 'Marketing & Kommunikation',
    beschreibung: 'Redaktionsmanagement, Content-Produktion und Vertriebssteuerung für Verlage.',
    schmerzen: ['Aufwendige Content-Produktion', 'Komplexes Redaktionsmanagement', 'Sinkende Printauflagen', 'Digitale Transformation'],
    ergebnisse: ['KI-unterstützte Content-Produktion', 'Digitales Redaktionssystem', 'Neue digitale Erlösmodelle', 'Schnelle digitale Transformation'],
    agenten: ['Der Schreiber', 'Der Analyst', 'Der Stratege', 'Der Regisseur'],
    stundenProWoche: { klein: 14, mittel: 24, gross: 38 },
  },
  {
    name: 'Fotografen & Videografen',
    slug: 'fotografen',
    kategorie: 'Marketing & Kommunikation',
    beschreibung: 'Auftragsmanagement, Bildbearbeitung-Workflows und Kundenkommunikation für Kreativschaffende.',
    schmerzen: ['Aufwendige Auftragsabwicklung', 'Zeitintensive Kundenkommunikation', 'Manuelle Rechnungsstellung', 'Fehlende Kundenbindung'],
    ergebnisse: ['Digitales Auftragsmanagement', 'Automatische Kundenkommunikation', 'Automatische Rechnungsstellung', 'Systematische Kundenbindung'],
    agenten: ['Der Empfänger', 'Der Buchhalter', 'Der Planer', 'Der Netzwerker'],
    stundenProWoche: { klein: 6, mittel: 10, gross: 16 },
  },
  {
    name: 'Film & TV-Produktion',
    slug: 'film-tv',
    kategorie: 'Marketing & Kommunikation',
    beschreibung: 'Produktionsplanung, Talentmanagement und Postproduktions-Workflows für Film- und TV-Produktionen.',
    schmerzen: ['Komplexe Produktionsplanung', 'Aufwendiges Talentmanagement', 'Schwierige Teamkoordination', 'Hoher Budgetdruck'],
    ergebnisse: ['Digitale Produktionsplanung', 'Strukturiertes Talentmanagement', 'Automatische Teamkoordination', 'Echtzeit-Budgetkontrolle'],
    agenten: ['Der Regisseur', 'Der Planer', 'Der Personalchef', 'Der Analyst'],
    stundenProWoche: { klein: 16, mittel: 27, gross: 43 },
  },
  {
    name: 'Musik & Entertainment',
    slug: 'musikbranche',
    kategorie: 'Marketing & Kommunikation',
    beschreibung: 'Tour-Management, Fan-Kommunikation und Lizenzmanagement für Musikunternehmen.',
    schmerzen: ['Aufwendiges Tour-Management', 'Manuelle Fan-Kommunikation', 'Komplexes Lizenzmanagement', 'Hoher administrativer Aufwand'],
    ergebnisse: ['Digitales Tour-Management', 'Automatische Fan-Kommunikation', 'KI-Lizenzmanagement', 'Deutlich weniger Administration'],
    agenten: ['Der Planer', 'Der Botschafter', 'Der Jurist', 'Der Empfänger'],
    stundenProWoche: { klein: 10, mittel: 17, gross: 27 },
  },
  {
    name: 'Spieleentwicklung & Gaming',
    slug: 'spieleentwicklung',
    kategorie: 'Marketing & Kommunikation',
    beschreibung: 'Community-Management, Spielerdaten-Analyse und Content-Pipeline für Gaming-Unternehmen.',
    schmerzen: ['Aufwendiges Community-Management', 'Hoher Content-Produktionsaufwand', 'Spielerbindungsprobleme', 'Komplexe Datenanalyse'],
    ergebnisse: ['KI-Community-Management', 'Automatisierte Content-Pipeline', 'Datengestützte Spielerbindung', 'Echtzeit-Spieleranalyse'],
    agenten: ['Der Botschafter', 'Der Analyst', 'Der Schreiber', 'Der Forscher'],
    stundenProWoche: { klein: 12, mittel: 20, gross: 32 },
  },
  {
    name: 'Künstler & Kreative',
    slug: 'kuenstler',
    kategorie: 'Marketing & Kommunikation',
    beschreibung: 'Portfolio-Management, Auftragsakquise und Kundenkommunikation für freischaffende Künstler.',
    schmerzen: ['Aufwendige Auftragsakquise', 'Manuelle Verwaltungsaufgaben', 'Fehlende Marketingstrategie', 'Schwierige Preisgestaltung'],
    ergebnisse: ['Systematische Auftragsakquise', 'Automatisierte Verwaltung', 'KI-Marketingstrategie', 'Datengestützte Preisgestaltung'],
    agenten: ['Der Netzwerker', 'Der Schreiber', 'Der Verkäufer', 'Der Analyst'],
    stundenProWoche: { klein: 6, mittel: 10, gross: 16 },
  },

  // ── GASTRONOMIE & TOURISMUS ──────────────────────────────────────────────

  {
    name: 'Gastronomie & Restaurants',
    slug: 'gastronomie',
    kategorie: 'Gastronomie & Tourismus',
    beschreibung: 'Reservierungsmanagement, Bestellabwicklung und Mitarbeitereinsatzplanung für Gastronomie.',
    schmerzen: ['Chaotisches Reservierungsmanagement', 'Aufwendige Dienstplanung', 'Hohe Lebensmittelverschwendung', 'Schlechte Online-Bewertungen'],
    ergebnisse: ['Digitales Reservierungssystem', 'KI-optimierte Dienstpläne', 'Optimierter Wareneinsatz', 'Automatisches Bewertungsmanagement'],
    agenten: ['Der Planer', 'Der Empfänger', 'Der Personalchef', 'Der Analyst'],
    stundenProWoche: { klein: 10, mittel: 17, gross: 27 },
  },
  {
    name: 'Hotels & Beherbergung',
    slug: 'hotels',
    kategorie: 'Gastronomie & Tourismus',
    beschreibung: 'Buchungsmanagement, Gästekommunikation und Revenue-Management für Hotels.',
    schmerzen: ['Aufwendiges Channel-Management', 'Manuelle Gästekommunikation', 'Komplexes Revenue-Management', 'Hoher Check-in/out-Aufwand'],
    ergebnisse: ['Automatisiertes Channel-Management', 'KI-Gästekommunikation 24/7', 'Dynamisches Revenue-Management', 'Digitaler Check-in/out'],
    agenten: ['Der Empfänger', 'Der Analyst', 'Der Planer', 'Der Botschafter'],
    stundenProWoche: { klein: 14, mittel: 24, gross: 38 },
  },
  {
    name: 'Catering & Eventgastronomie',
    slug: 'catering',
    kategorie: 'Gastronomie & Tourismus',
    beschreibung: 'Eventplanung, Menükonfiguration und Lieferantenkoordination für Cateringunternehmen.',
    schmerzen: ['Komplexe Eventplanung', 'Aufwendige Menükonfiguration', 'Schwierige Lieferantenkoordination', 'Hoher Kommunikationsaufwand mit Kunden'],
    ergebnisse: ['Digitale Eventplanung', 'KI-Menükonfiguration', 'Automatische Lieferantenkoordination', 'Strukturierte Kundenkommunikation'],
    agenten: ['Der Planer', 'Der Einkäufer', 'Der Empfänger', 'Der Verkäufer'],
    stundenProWoche: { klein: 10, mittel: 17, gross: 27 },
  },
  {
    name: 'Reisebüros',
    slug: 'reisebueros',
    kategorie: 'Gastronomie & Tourismus',
    beschreibung: 'Reiseplanung, Kundenkommunikation und Buchungsabwicklung für Reisebüros.',
    schmerzen: ['Aufwendige Reiseplanung', 'Hoher Buchungsaufwand', 'Starker Online-Wettbewerb', 'Manuelle Kundenkommunikation'],
    ergebnisse: ['KI-Reiseplanung', 'Automatisierte Buchungsabwicklung', 'Klare Differenzierung online', 'Automatische Kundenkommunikation'],
    agenten: ['Der Planer', 'Der Empfänger', 'Der Verkäufer', 'Der Forscher'],
    stundenProWoche: { klein: 8, mittel: 14, gross: 22 },
  },
  {
    name: 'Eventmanagement',
    slug: 'eventmanagement',
    kategorie: 'Gastronomie & Tourismus',
    beschreibung: 'Eventlogistik, Teilnehmermanagement und Sponsorenakquise für Eventmanagement-Unternehmen.',
    schmerzen: ['Komplexe Eventlogistik', 'Aufwendiges Teilnehmermanagement', 'Schwierige Sponsorenakquise', 'Hoher Kommunikationsaufwand'],
    ergebnisse: ['Digitale Eventlogistik', 'Automatisiertes Teilnehmermanagement', 'Systematische Sponsorenakquise', 'Strukturierte Eventkommunikation'],
    agenten: ['Der Planer', 'Der Moderator', 'Der Verkäufer', 'Der Empfänger'],
    stundenProWoche: { klein: 12, mittel: 20, gross: 32 },
  },
  {
    name: 'Freizeit & Unterhaltung',
    slug: 'freizeitparks',
    kategorie: 'Gastronomie & Tourismus',
    beschreibung: 'Besuchermanagement, Online-Ticketing und Marketingautomatisierung für Freizeiteinrichtungen.',
    schmerzen: ['Aufwendiges Ticketmanagement', 'Hoher Besucherservice-Aufwand', 'Schwierige Kapazitätsplanung', 'Manuelle Marketingkampagnen'],
    ergebnisse: ['Digitales Online-Ticketing', 'KI-Besucherservice', 'KI-Kapazitätsplanung', 'Automatisierte Marketingkampagnen'],
    agenten: ['Der Empfänger', 'Der Planer', 'Der Analyst', 'Der Botschafter'],
    stundenProWoche: { klein: 10, mittel: 17, gross: 27 },
  },
  {
    name: 'Fitnessstudios & Sport',
    slug: 'fitnessstudios',
    kategorie: 'Gastronomie & Tourismus',
    beschreibung: 'Mitgliederverwaltung, Kursplanung und Kundenbindung für Fitnessstudios.',
    schmerzen: ['Aufwendige Mitgliederverwaltung', 'Hohe Kündigungsrate', 'Manuelle Kursplanung', 'Fehlende Kundenbindung'],
    ergebnisse: ['Automatische Mitgliederverwaltung', 'Proaktive Churn-Prävention', 'KI-Kursplanung', 'Systematische Kundenbindung'],
    agenten: ['Der Empfänger', 'Der Planer', 'Der Analyst', 'Der Netzwerker'],
    stundenProWoche: { klein: 8, mittel: 14, gross: 22 },
  },
  {
    name: 'Kosmetik & Beauty',
    slug: 'kosmetik',
    kategorie: 'Gastronomie & Tourismus',
    beschreibung: 'Terminmanagement, Produktberatung und Kundenbindung für Kosmetikstudios.',
    schmerzen: ['Aufwendige Terminverwaltung', 'Hohe No-Show-Quote', 'Fehlende Kundenbindung', 'Manuelle Produktberatung'],
    ergebnisse: ['Online-Terminbuchung 24/7', '30% weniger No-Shows', 'Automatische Kundenbindung', 'KI-Produktberatung'],
    agenten: ['Der Planer', 'Der Empfänger', 'Der Netzwerker', 'Der Verkäufer'],
    stundenProWoche: { klein: 6, mittel: 10, gross: 16 },
  },
  {
    name: 'Friseure & Salons',
    slug: 'friseure',
    kategorie: 'Gastronomie & Tourismus',
    beschreibung: 'Terminbuchung, Kundenbindung und Social-Media-Management für Friseurbetriebe.',
    schmerzen: ['Viele Telefon-Terminanfragen', 'Hohe No-Show-Quote', 'Fehlende Online-Präsenz', 'Schwache Kundenbindung'],
    ergebnisse: ['Online-Buchung rund um die Uhr', 'Automatische Terminerinnerungen', 'Starke Social-Media-Präsenz', 'Loyales Stammkundenprogramm'],
    agenten: ['Der Planer', 'Der Botschafter', 'Der Empfänger', 'Der Netzwerker'],
    stundenProWoche: { klein: 5, mittel: 9, gross: 14 },
  },
  {
    name: 'Tattoo Studios',
    slug: 'tattoo-studios',
    kategorie: 'Gastronomie & Tourismus',
    beschreibung: 'Terminmanagement, Kundenkommunikation und Portfolio-Marketing für Tattoo-Studios.',
    schmerzen: ['Aufwendige Terminkoordination', 'Viele Anfragen ohne Buchung', 'Fehlende Online-Sichtbarkeit', 'Manuelle Kundenverwaltung'],
    ergebnisse: ['Digitale Terminkoordination', 'Automatische Anfragenbearbeitung', 'Starke Online-Sichtbarkeit', 'Automatische Kundenverwaltung'],
    agenten: ['Der Planer', 'Der Empfänger', 'Der Botschafter', 'Der Netzwerker'],
    stundenProWoche: { klein: 5, mittel: 8, gross: 13 },
  },
  {
    name: 'Sportvereine',
    slug: 'sportvereine',
    kategorie: 'Gastronomie & Tourismus',
    beschreibung: 'Mitgliederverwaltung, Spielbetrieb-Koordination und Vereinskommunikation für Sportvereine.',
    schmerzen: ['Aufwendige Mitgliederverwaltung', 'Schwierige Spielplankoordination', 'Manuelle Beitragsverwaltung', 'Fehlende Vereinskommunikation'],
    ergebnisse: ['Digitale Mitgliederverwaltung', 'Automatische Spielplanverwaltung', 'Automatisches Beitragsmanagement', 'Vereins-Newsletter automatisch'],
    agenten: ['Der Empfänger', 'Der Planer', 'Der Buchhalter', 'Der Moderator'],
    stundenProWoche: { klein: 6, mittel: 10, gross: 16 },
  },

  // ── BILDUNG & SOZIALES ───────────────────────────────────────────────────

  {
    name: 'Bildung & Weiterbildung',
    slug: 'bildung-weiterbildung',
    kategorie: 'Bildung & Soziales',
    beschreibung: 'Kursmanagement, Teilnehmerkommunikation und Zertifizierungsprozesse für Bildungsanbieter.',
    schmerzen: ['Aufwendige Kursverwaltung', 'Hoher Kommunikationsaufwand', 'Manuelle Zertifizierungsprozesse', 'Fehlende Lernfortschrittsanalyse'],
    ergebnisse: ['Digitales Kursmanagement', 'Automatische Teilnehmerkommunikation', 'Digitale Zertifizierungsprozesse', 'KI-Lernfortschrittsanalyse'],
    agenten: ['Der Trainer', 'Der Planer', 'Der Schreiber', 'Der Analyst'],
    stundenProWoche: { klein: 10, mittel: 17, gross: 27 },
  },
  {
    name: 'Fahrschulen',
    slug: 'fahrschulen',
    kategorie: 'Bildung & Soziales',
    beschreibung: 'Terminplanung, Lernfortschrittsverwaltung und Prüfungsanmeldung für Fahrschulen.',
    schmerzen: ['Aufwendige Fahrstundenplanung', 'Manuelle Lernfortschrittsdokumentation', 'Komplizierte Prüfungsanmeldung', 'Hoher Verwaltungsaufwand'],
    ergebnisse: ['Automatische Fahrstundenplanung', 'Digitale Lernfortschrittsanalyse', 'Vereinfachte Prüfungsanmeldung', '40% weniger Verwaltungsaufwand'],
    agenten: ['Der Planer', 'Der Trainer', 'Der Empfänger', 'Der Schreiber'],
    stundenProWoche: { klein: 7, mittel: 12, gross: 19 },
  },
  {
    name: 'Schulen & Gymnasien',
    slug: 'schulen',
    kategorie: 'Bildung & Soziales',
    beschreibung: 'Elternkommunikation, Stundenplanverwaltung und Lehrerkoordination für Schulen.',
    schmerzen: ['Aufwendige Elternkommunikation', 'Komplexe Stundenplanverwaltung', 'Schwierige Lehrerkoordination', 'Hoher Verwaltungsaufwand'],
    ergebnisse: ['Automatische Elternkommunikation', 'Digitale Stundenplanverwaltung', 'Strukturierte Lehrerkoordination', 'Deutlich weniger Verwaltung'],
    agenten: ['Der Empfänger', 'Der Planer', 'Der Moderator', 'Der Schreiber'],
    stundenProWoche: { klein: 12, mittel: 20, gross: 32 },
  },
  {
    name: 'Universitäten & Hochschulen',
    slug: 'universitaeten',
    kategorie: 'Bildung & Soziales',
    beschreibung: 'Studierendenverwaltung, Forschungsunterstützung und Campuskommunikation für Hochschulen.',
    schmerzen: ['Aufwendige Studierendenverwaltung', 'Hoher Forschungsaufwand', 'Komplexe Campuskommunikation', 'Viele administrative Prozesse'],
    ergebnisse: ['Digitale Studierendenverwaltung', 'KI-Forschungsunterstützung', 'Automatisierte Campuskommunikation', 'Schlankere administrative Prozesse'],
    agenten: ['Der Forscher', 'Der Analyst', 'Der Schreiber', 'Der Moderator'],
    stundenProWoche: { klein: 18, mittel: 30, gross: 48 },
  },
  {
    name: 'Wohlfahrtsverbände & NGOs',
    slug: 'wohlfahrtsverbaende',
    kategorie: 'Bildung & Soziales',
    beschreibung: 'Spendenmanagement, Fördermittelanträge und Freiwilligenkoordination für gemeinnützige Organisationen.',
    schmerzen: ['Aufwendiges Spendenmanagement', 'Zeitintensive Fördermittelanträge', 'Schwierige Freiwilligenkoordination', 'Hoher Berichtsaufwand'],
    ergebnisse: ['Digitales Spendenmanagement', 'KI-Fördermittelanträge', 'Automatische Freiwilligenkoordination', 'Strukturiertes Reporting'],
    agenten: ['Der Buchhalter', 'Der Schreiber', 'Der Personalchef', 'Der Analyst'],
    stundenProWoche: { klein: 10, mittel: 17, gross: 27 },
  },
  {
    name: 'Verbände & Kammern',
    slug: 'verbände',
    kategorie: 'Bildung & Soziales',
    beschreibung: 'Mitgliederverwaltung, Veranstaltungsorganisation und Interessenvertretung für Verbände.',
    schmerzen: ['Aufwendige Mitgliederverwaltung', 'Zeitintensive Veranstaltungsorganisation', 'Komplexe Gremienarbeit', 'Hoher Kommunikationsaufwand'],
    ergebnisse: ['Digitale Mitgliederverwaltung', 'Automatisierte Veranstaltungsorganisation', 'Strukturierte Gremienarbeit', 'Effiziente Mitgliederkommunikation'],
    agenten: ['Der Empfänger', 'Der Planer', 'Der Moderator', 'Der Schreiber'],
    stundenProWoche: { klein: 10, mittel: 17, gross: 27 },
  },
  {
    name: 'Berufsverbände & Innungen',
    slug: 'berufsverbände',
    kategorie: 'Bildung & Soziales',
    beschreibung: 'Mitgliederservice, Weiterbildungsmanagement und Lobbyarbeit für Berufsverbände.',
    schmerzen: ['Aufwendiger Mitgliederservice', 'Komplexes Weiterbildungsmanagement', 'Zeitintensive Öffentlichkeitsarbeit', 'Viele Mitgliederanfragen'],
    ergebnisse: ['Automatischer Mitgliederservice', 'Digitales Weiterbildungsmanagement', 'KI-Öffentlichkeitsarbeit', 'Automatische Anfragenbearbeitung'],
    agenten: ['Der Empfänger', 'Der Trainer', 'Der Botschafter', 'Der Schreiber'],
    stundenProWoche: { klein: 8, mittel: 14, gross: 22 },
  },
  {
    name: 'Kirchen & Religionsgemeinschaften',
    slug: 'kirchen-religionsgemeinschaften',
    kategorie: 'Bildung & Soziales',
    beschreibung: 'Gemeindeverwaltung, Veranstaltungsmanagement und Mitgliederkommunikation für Religionsgemeinschaften.',
    schmerzen: ['Aufwendige Gemeindeverwaltung', 'Manuelle Veranstaltungsplanung', 'Fehlende digitale Kommunikation', 'Hoher ehrenamtlicher Aufwand'],
    ergebnisse: ['Digitale Gemeindeverwaltung', 'Automatische Veranstaltungsplanung', 'Moderner digitaler Newsletter', 'Entlastung der Ehrenamtlichen'],
    agenten: ['Der Empfänger', 'Der Planer', 'Der Schreiber', 'Der Moderator'],
    stundenProWoche: { klein: 6, mittel: 10, gross: 16 },
  },
  {
    name: 'Museen & Kultureinrichtungen',
    slug: 'museen-kultur',
    kategorie: 'Bildung & Soziales',
    beschreibung: 'Besuchermanagement, Ausstellungsplanung und Fördermittelmanagement für Kultureinrichtungen.',
    schmerzen: ['Aufwendiges Besuchermanagement', 'Komplexe Ausstellungsplanung', 'Zeitintensive Fördermittelanträge', 'Schwierige Zielgruppenansprache'],
    ergebnisse: ['Digitales Besuchermanagement', 'KI-Ausstellungsplanung', 'Automatisierte Fördermittelanträge', 'Zielgruppengerechte Kommunikation'],
    agenten: ['Der Planer', 'Der Schreiber', 'Der Analyst', 'Der Botschafter'],
    stundenProWoche: { klein: 10, mittel: 17, gross: 27 },
  },
  {
    name: 'Bibliotheken & Archive',
    slug: 'bibliotheken',
    kategorie: 'Bildung & Soziales',
    beschreibung: 'Bestandsverwaltung, Nutzerkommunikation und Digitalisierungsprozesse für Bibliotheken.',
    schmerzen: ['Aufwendige Bestandsverwaltung', 'Manuelle Ausleihprozesse', 'Komplexe Digitalisierungsprojekte', 'Fehlende digitale Services'],
    ergebnisse: ['Digitale Bestandsverwaltung', 'Automatisierte Ausleihprozesse', 'KI-unterstützte Digitalisierung', 'Moderner digitaler Nutzerservice'],
    agenten: ['Der Analyst', 'Der Schreiber', 'Der Empfänger', 'Der Forscher'],
    stundenProWoche: { klein: 8, mittel: 14, gross: 22 },
  },
  {
    name: 'Archiv & Dokumentenmanagement',
    slug: 'archiv-dokumentation',
    kategorie: 'Bildung & Soziales',
    beschreibung: 'Dokumentenklassifikation, Archivierung und Suchlösungen für Archiv- und Dokumentenmanagement-Dienstleister.',
    schmerzen: ['Manuelle Dokumentenklassifikation', 'Schwierige Suche im Archiv', 'Aufwendige Digitalisierung', 'Hoher Speicheraufwand'],
    ergebnisse: ['KI-Dokumentenklassifikation', 'Semantische Volltextsuche', 'Automatisierte Digitalisierungspipeline', 'Optimiertes Speichermanagement'],
    agenten: ['Der Analyst', 'Der Forscher', 'Der Schreiber', 'Der Techniker'],
    stundenProWoche: { klein: 10, mittel: 17, gross: 27 },
  },

  // ── DIENSTLEISTUNGEN ─────────────────────────────────────────────────────

  {
    name: 'Reinigungsunternehmen',
    slug: 'reinigungsunternehmen',
    kategorie: 'Dienstleistungen',
    beschreibung: 'Einsatzplanung, Qualitätskontrolle und Kundenkommunikation für Reinigungsdienstleister.',
    schmerzen: ['Aufwendige Einsatzplanung', 'Schwierige Qualitätskontrolle', 'Hohe Mitarbeiterfluktuation', 'Aufwendige Kundenkommunikation'],
    ergebnisse: ['KI-optimierte Einsatzplanung', 'Digitale Qualitätschecks', 'Bessere Mitarbeiterbindung', 'Automatische Kundenkommunikation'],
    agenten: ['Der Planer', 'Der Personalchef', 'Der Empfänger', 'Der Analyst'],
    stundenProWoche: { klein: 8, mittel: 14, gross: 22 },
  },
  {
    name: 'Sicherheitsdienste',
    slug: 'sicherheitsdienste',
    kategorie: 'Dienstleistungen',
    beschreibung: 'Schichtplanung, Einsatzdokumentation und Kundenkommunikation für Sicherheitsdienstleister.',
    schmerzen: ['Komplexe Schichtplanung', 'Aufwendige Einsatzdokumentation', 'Hoher Koordinationsaufwand', 'Manuelle Berichterstellung'],
    ergebnisse: ['KI-Schichtplanung', 'Automatische Einsatzdokumentation', 'Zentrale Koordinationsplattform', 'Automatische Kundenberichte'],
    agenten: ['Der Planer', 'Der Sicherheitschef', 'Der Schreiber', 'Der Personalchef'],
    stundenProWoche: { klein: 10, mittel: 17, gross: 27 },
  },
  {
    name: 'Personalvermittlung',
    slug: 'personalvermittlung',
    kategorie: 'Dienstleistungen',
    beschreibung: 'Kandidatenmanagement, Matching-Prozesse und Kundenbetreuung für Personalvermittler.',
    schmerzen: ['Aufwendiges Kandidatenscreening', 'Schlechte Matching-Qualität', 'Zeitintensive Kundenbetreuung', 'Hoher Verwaltungsaufwand'],
    ergebnisse: ['KI-Kandidatenscreening', 'Intelligentes Matching', 'Automatische Kundenbetreuung', '50% weniger Verwaltungsaufwand'],
    agenten: ['Der Personalchef', 'Der Analyst', 'Der Empfänger', 'Der Netzwerker'],
    stundenProWoche: { klein: 12, mittel: 20, gross: 32 },
  },
  {
    name: 'Landwirtschaft & Agrar',
    slug: 'landwirtschaft',
    kategorie: 'Dienstleistungen',
    beschreibung: 'Betriebsplanung, Fördermittelmanagement und Dokumentation für landwirtschaftliche Betriebe.',
    schmerzen: ['Aufwendige Fördermittelanträge', 'Komplexe Betriebsdokumentation', 'Wetterabhängige Planung', 'Hoher Verwaltungsaufwand'],
    ergebnisse: ['KI-Fördermittelanträge', 'Automatische Betriebsdokumentation', 'KI-Wetterbasierte Planung', '40% weniger Verwaltungsaufwand'],
    agenten: ['Der Schreiber', 'Der Planer', 'Der Analyst', 'Der Jurist'],
    stundenProWoche: { klein: 8, mittel: 14, gross: 22 },
  },
  {
    name: 'Gartenbau & Landschaftsbau',
    slug: 'gartenbau',
    kategorie: 'Dienstleistungen',
    beschreibung: 'Auftragsplanung, Angebotserstellung und Kundenkommunikation für Gartenbauunternehmen.',
    schmerzen: ['Saisonale Auftragsschwankungen', 'Aufwendige Angebotserstellung', 'Manuelle Ressourcenplanung', 'Fehlende Kundenbindung'],
    ergebnisse: ['Bessere Saisonplanung', 'Schnelle digitale Angebote', 'KI-Ressourcenplanung', 'Systematische Kundenbindung'],
    agenten: ['Der Planer', 'Der Verkäufer', 'Der Empfänger', 'Der Einkäufer'],
    stundenProWoche: { klein: 7, mittel: 12, gross: 19 },
  },
  {
    name: 'Forstwirtschaft & Holz',
    slug: 'forstwirtschaft',
    kategorie: 'Dienstleistungen',
    beschreibung: 'Bestandsverwaltung, Nachhaltigkeitsdokumentation und Vermarktung für Forstwirtschaftsbetriebe.',
    schmerzen: ['Komplexe Bestandsverwaltung', 'Aufwendige Nachhaltigkeitsdokumentation', 'Schwierige Holzvermarktung', 'Hoher Regulierungsaufwand'],
    ergebnisse: ['Digitale Bestandsverwaltung', 'Automatische Nachhaltigkeitsberichte', 'Optimierte Holzvermarktung', 'KI-Regulierungsunterstützung'],
    agenten: ['Der Analyst', 'Der Schreiber', 'Der Jurist', 'Der Einkäufer'],
    stundenProWoche: { klein: 8, mittel: 14, gross: 22 },
  },
  {
    name: 'Nachhaltigkeit & ESG',
    slug: 'nachhaltigkeit',
    kategorie: 'Dienstleistungen',
    beschreibung: 'ESG-Reporting, Nachhaltigkeitsstrategien und Stakeholder-Kommunikation für nachhaltigkeitsorientierte Unternehmen.',
    schmerzen: ['Aufwendiges ESG-Reporting', 'Komplexe Datenerhebung', 'Hoher Regulierungsaufwand', 'Schwierige Stakeholder-Kommunikation'],
    ergebnisse: ['Automatisiertes ESG-Reporting', 'KI-Datenerhebung und -analyse', 'Compliance-konforme Dokumentation', 'Strukturierte Stakeholder-Kommunikation'],
    agenten: ['Der Analyst', 'Der Schreiber', 'Der Jurist', 'Der Stratege'],
    stundenProWoche: { klein: 10, mittel: 17, gross: 27 },
  },
]

export function getAllBrancheSlugs(): string[] {
  return branchen.map((b) => b.slug)
}

export function getBrancheBySlug(slug: string): Branche | undefined {
  return branchen.find((b) => b.slug === slug)
}

export function getAllBranchen(): Branche[] {
  return branchen
}

export function getBranchenByKategorie(kategorie: string): Branche[] {
  return branchen.filter((b) => b.kategorie === kategorie)
}

export default branchen
