S = []  # (stufe_id, titel, untertitel, rows)
# row: (nr, paket, heute, loesung, wer, pushes, status)
S.append(("s0","Stufe 0 · Sicherheit","Kontoübernahme und Rechtsrisiko – vor allem anderen",[
("164b","Zwei-Faktor im Team","Mitarbeiter ohne Handy oder Notfall-Code konnten nur über das Supabase-Dashboard wieder hinein; niemand im Betrieb konnte helfen.","Chef und eine Vertretung setzen die Zwei-Faktor-Anmeldung zurück, der Betreiber hat eine eigene Tür im Command Center, Hilfe-Anfrage per Glocke.","G","1","live"),
("169","Konto-Schutz","Die Mitarbeiter-Einladung übernahm fremde Konten per E-Mail. Ein Chef konnte über die Login-Verknüpfung das Passwort fremder Personen setzen und ihre Zwei-Faktor löschen. Jeder Nutzer konnte sich selbst zum Admin machen. 24 Datenbank-Funktionen waren ohne Anmeldung aufrufbar.","Bestehende Konten werden nie übernommen, jedes Zurücksetzen prüft das Ziel-Konto, die Verknüpfung setzt nur noch der Server, Rolle und Tarif sind gesperrt, Funktionen nur noch mit Anmeldung bzw. nur für den Server.","G","1","live"),
("170","Admin-Doppelschloss","8 Admin-Routen prüften nur die Rolle „admin“. Der Website-Modus ließ ohne gesetzte Variable jeden Angemeldeten durch. Zwei Routen hatten ein eigenes Schloss ohne Zwei-Faktor.","Alle Admin-Wege prüfen Rolle, Betreiber-Kennung und Zwei-Faktor über eine zentrale Stelle; ein Test verhindert neue Lücken.","C","1","live"),
("173","Werbe-Mails rechtssicher","Autoresponder schickt Werbeserien an frei eingetippte Adressen ohne Einwilligung. Bewertungs-Bitten ohne Einwilligung und ohne Abmeldelink. Jede Website-Anfrage startet ungefragt eine Werbeserie. Termin-Nachfass ohne Abmeldelink, der Name aus dem Formular geht ungeschützt in die Mail (Phishing-Gefahr). Mails aus Abläufen kommen als „ARGONAUT OS“, Antworten landen bei info@. Abmeldung wirkt nur in einem Kanal. Newsletter prüft die Bestätigung nicht.","Werbung nur an bestätigte Einwilligungen, Abmeldelink und Widerspruchshinweis in jeder Werbe-Mail, eigenes Häkchen für die Dossier-Serie, Namen geschützt, Absender und Antwortadresse des Betriebs, eine Abmeldung stoppt alle Kanäle.","C","1","live"),
]))
S.append(("s1","Stufe 1 · Vor dem ersten weiteren Kunden","Mandantentrennung, Geld, KI-Regeln, Datenschutz, Testtag-Vorbereitung",[
("174","Mandanten-Lücken in der Datenbank","Ehemalige Mitarbeiter oder Fremde mit Kanal-Kennung können Team-Chat-Kanälen selbst beitreten und alles lesen. Ein Chef kann sich bezahlte Module selbst freischalten. Mitarbeiter können HR-Einträge bei einem fremden Betrieb anlegen. Chat-Absender lassen sich fälschen.","Beitritt nur im eigenen Betrieb, Modul-Freischaltung nur über den Betreiber, HR-Einträge immer beim eigenen Betrieb, Absender = angemeldete Person. SQL getrennt.","G","1","live"),
("175","Geld-Routen absichern","Rechnungs-, Mahnungs- und Auftragsbestätigungs-PDFs lassen sich ohne Login erzeugen. Die Kasse kann Lager auf fremde Artikel buchen. „Rechnung senden“ versendet auch für Mitarbeiter ohne Abrechnungsrecht. Ein Mitarbeiter kann ein ARGONAUT-Abo mit SEPA anlegen. „Rechnung neu berechnen“ prüft den Besitzer nicht.","Login-Pflicht für alle PDF-Routen, Artikel nur aus dem eigenen Betrieb, Senden nur mit Abrechnungsrecht, Abo nur durch den Chef, Besitzer-Prüfung in der Datenbank-Funktion.","G","1","nächster"),
("176","KI-Regeln einhalten","Die KI schätzt Marktpreise für Auftragspositionen (gegen die Grundregel). Die HR-Auswertung schickt Krankheitsmuster an die KI, der Dashboard-Chat die Namen Krankgemeldeter. Stapel-Aufträge fehlen im KI-Kostenprotokoll.","Platzhalter „Preis bitte ergänzen“, keine Krankheitsdaten an die KI (nur Anzahlen), Stapel-Kosten im Protokoll.","C","1","offen"),
("177","Kündigungs-Sperre wirksam","Die Sperre für gekündigte Kunden liest eine Liste, in die nie jemand etwas einträgt. Gekündigte Kunden und ihre Mitarbeiter arbeiten weiter.","Kündigung trägt automatisch ein, die Sperre gilt auch für die Mitarbeiter und für Schnittstellen.","G","1","offen"),
("178","Datenschutzerklärung neu","Die Erklärung sagt „Anthropic anonymisiert“ und „Voyage entfernt Personenbezug“ – beides stimmt nicht. Resend, Ersatz-KI, PDF-Server, WhatsApp, Social-Schnittstellen, Messung und die Gesundheitsmodule fehlen.","Erklärung vollständig und richtig neu fassen, danach Anwalt; Baukasten-Vorlage für Kundenseiten mitziehen.","G","1","offen"),
("179","Musterbetrieb XXL","Für den Testtag gibt es keinen Betrieb, in dem alle Module mit Daten gefüllt sind; jede Seite müsste von Hand befüllt werden.","Ein vollständiger Musterbetrieb mit Beispieldaten in allen Modulen, per Knopf anlegbar und wieder löschbar.","C","2","offen"),
("180","Fachbeschreibung Elektriker","Das Dossier ist ein Werbetext; eine Beschreibung, was das System für eine Branche wirklich kann, fehlt.","8–12 Seiten für Laien, nur Gebautes, Vorgebautes als „in Vorbereitung“; danach Vorlage für alle Branchen.","C","0","offen"),
("188","Voice Layer Stufe 1","Vorlesen nur mit der Browser-Stimme, klingt je Gerät anders und robotisch.","Deine geklonte Stimme über ElevenLabs, nur mit Login, Längen- und Tagesdeckel, Browser-Stimme bleibt Rückfall.","C","1","offen"),
]))
S.append(("s2","Stufe 2 · Bald","Rechte sauber ziehen, Lücken aus alten Modulen schließen",[
("181","Geld- und Personal-Seiten auf „Betrieb“","Auf 13 Seiten (Abo-Rechnungen, Eingangsbelege, Ausgaben, Reisekosten, Mitglieder, Personal, Provisionen, Nachkalkulation, Ernte-Zahlungen, Portal-Zugänge, Verträge, Fördervorhaben, Rückholung) speichern Mitarbeiter unter eigener Kennung – der Chef sieht diese Einträge nicht.","Speichern immer für den Betrieb, wie in Paket 165; SQL getrennt, weil es Mitarbeiter ohne Schreibrecht betrifft.","G","2","offen"),
("182","Angebot-Link erst ab „versendet“","Ein Angebot im Entwurf ist per Link annehmbar, das Kundenportal zeigt Entwürfe, die Annahme speichert keinen Namen.","Link und Portal erst ab Status „versendet“, Annahme mit Name und Zeitpunkt.","G","1","offen"),
("183","WhatsApp-Anmeldung mit Bestätigung","Eine Nummer ist nach dem Formular sofort aktiv; Dritte können fremde Nummern eintragen.","Nummer erst aktiv, wenn die Person per WhatsApp antwortet; Nachweis gespeichert.","C","1","offen"),
("184","Dateien, Uploads, IBAN, Import","Einige Download-Wege vertrauen gespeicherten Pfaden – bei bekanntem Dateinamen fremde Datei abrufbar. Eine Tresenkraft lädt IBANs mit. Der Import erkennt Bank- und Werbe-Spalten nur am Namen. Speicher ohne feste Größen- und Typgrenzen, AU-Bescheinigungen unverschlüsselt.","Pfad muss zum Betrieb gehören, IBAN nur für berechtigte Rollen, Inhalte auf IBAN-Muster prüfen, Grenzen je Speicher, AU verschlüsselt.","C","1","offen"),
("185","Schreibrechte der Mitarbeiter je Modul","An rund 175 Stellen dürfen Mitarbeiter über die Datenbank schreiben, auch wenn sie im Modul nur lesen dürfen. Lagerbewegungen dürfen sie löschen (GoBD). Abo-Rechnungen ohne Abrechnungsrecht.","Schreiben nur mit Modul-Schreibrecht, Löschen von Buchungen nur Chef, Abo-Rechnungen nur mit Abrechnungsrecht – schrittweise, SQL getrennt.","G","2","offen"),
("186","Abläufe-Rest","Abläufe lassen sich nicht löschen. Ein abgestürzter Lauf bleibt ewig auf „läuft“. Ein nicht erreichbarer Webhook-Empfänger stoppt den Lauf ohne Neuversuch.","Löschen mit Rückfrage (Protokoll bleibt), hängende Läufe nach 2 Std. auf Fehler + Glocke, 3 Neuversuche über 24 Std.","C","1","offen"),
("187","Sammelpaket klein","Prüf-Fälligkeiten rutschen einen Tag zurück und Monate laufen über (31.01. + 1 Monat = 03.03.). MRR-Kachel rechnet mit alten Preisen. Rechnungs-Knöpfe beim Mitarbeiter sichtbar. Artikel-Import überschreibt Filialbestände. Vereine bekommen Vertragsart „Studio“. Videos laden ohne Zwei-Klick. Alte Crons nehmen das Geheimnis per URL. Keine volle CSP. 17 npm-Warnungen.","Jeden Punkt einzeln beheben, mit Tests; CSP zuerst im Beobachtungsmodus.","C","2","offen"),
("164·3","Zwei-Faktor auch in der Datenbank","Zwei-Faktor schützt nur die Seiten; mit gestohlenem Passwort sind Schnittstellen und Datenbank weiter voll nutzbar.","Datenbank-Regeln verlangen den bestätigten Code, danach Pflicht für alle einschalten. Hohes Aussperr-Risiko, mit Rückweg.","G","1","offen"),
("189","Voice Layer Stufe 2","Jede Wiedergabe erzeugt die Stimme neu und kostet jedes Mal.","Zwischenspeicher im privaten Speicher, gleiche Texte kosten nichts mehr.","C","1","offen"),
("35–40","DSGVO-Werkzeuge (72er-Liste)","Verzeichnis und Auskunft haben 54 Lücken, es gibt keinen Löschweg für Leads, Webinar-Daten werden gelöscht statt gesperrt, keine Sperrung mit Fristen.","Vollständiges Verzeichnis mit Mustertexten, Löschweg, Sperren statt Löschen mit Fristen-Automatik – nach dem Anwalt.","C","2","wartet auf Anwalt"),
]))
S.append(("s3","Stufe 3 · Neue Funktionen","Fehlt heute komplett",[
("B1","Bausteine Presse, SEO-Texter, E-Book, Strategie, Social","Diese Bausteine gibt es noch nicht.","Je Baustein eine Seite mit Vorlagen, Entwurf per KI, nichts wird ungeprüft veröffentlicht; KI-Kennzeichnung.","C","3","offen"),
("B2","KI-Telefonassistent","Anrufe außerhalb der Zeiten gehen verloren; kein Telefon-Baustein.","Partner Retell oder Vapi, Termine und Anfragen landen im System, KI-Hinweis am Telefon.","G","2","wartet auf Partner"),
("B3","Website-Texte aus Firmenwissen","Kundenseiten müssen von Hand betextet werden.","Texte aus dem hinterlegten Firmenwissen vorschlagen, Freigabe durch den Betrieb.","C","1","offen"),
("B4","Shop aus Inventar","Artikel müssen einzeln für den Shop freigeschaltet werden.","Artikel mit einem Klick bzw. per Auswahl in den Shop übernehmen.","C","1","offen"),
("B5","Branchenverzeichnis-Eintrag","Einträge in Verzeichnissen macht jeder Betrieb selbst.","Eintrag mit einem Klick aus den Firmendaten vorbereiten.","C","1","offen"),
("B6","Mitbewerber-Funktionen Top 10","Unklar, welche gängigen Funktionen führender Mitbewerber noch fehlen.","Recherche + Lückenliste, fehlende Funktionen einplanen (Namen nie nach außen).","C","1","offen"),
("B7","Eigene Absender-Domain je Betrieb","Kunden-Mails gehen von noreply@argonaut-os.com.","Eigene Domain je Betrieb über Resend, Einrichtung durch den Betreiber.","G","1","offen"),
("B8","Echte Anmeldung Marketing-Plattformen","Zugänge zu Meta, Google, LinkedIn, TikTok werden von Hand eingetragen.","Anmeldung per Plattform-Login (OAuth), Zugänge verschlüsselt.","G","2","wartet auf App-Prüfung"),
("B9","Paket 2 Andocken","Aufmaß fließt nicht in die Kalkulation, Ist-Zeiten nicht zurück in den Kalkulator, die Marge ist nicht die echte.","Aufmaß-Formel, Ist-Zeiten und echte Marge verbinden, Hinweise anzeigen.","G","2","offen"),
("B10","Fernhilfe: Bildschirm teilen","Braucht ein Mitarbeiter oder Kunde Hilfe, kann niemand sehen, was er gerade auf dem Bildschirm hat; es bleibt beim Beschreiben am Telefon.","Knopf „Hilfe anfordern“: die Person teilt selbst ihren Bildschirm oder nur das ARGONAUT-Fenster, der Helfer schaut per Link live zu; nur nach Klick und Zustimmung, rotes Banner solange geteilt wird, jederzeit beenden, keine Aufzeichnung, Passwort- und Bankfelder verdeckt.","C","2","offen"),
]))
S.append(("s4","Externe Partner mit eigenem Push","Schnittstellen, die erst mit Vertrag scharf werden",[
("E1","finAPI – Bankumsätze automatisch","Bankumsätze nur per Datei-Import (CSV, CAMT, MT940).","Automatischer Abruf über finAPI, Abgleich mit offenen Rechnungen – Lizenzmodell vorher klären.","G","2","wartet auf Vertrag"),
("E2","Echte Kassen-TSE","Die Kasse läuft nur im Demo-Modus ohne echte TSE.","Anbindung fiskaly oder Deutsche Fiskal, Kassen-Meldung.","G","1","wartet auf Konto"),
("E3","DATEVconnect","DATEV nur als Datei-Export.","Direkte Übergabe an den Steuerberater über DATEVconnect.","C","1","wartet auf Zugang"),
("E4","Shop- und Versand-Schnittstellen","Shopware, Shopify, WooCommerce und DHL sind gebaut, aber nie mit echtem Konto getestet.","Test mit echten Konten, Fehler beheben.","C","1","wartet auf Testkonten"),
]))
